import 'package:capsa/common/responsive.dart';
import 'package:capsa/vendor-new/model/bids_model.dart';
import 'package:flutter/material.dart';


import 'package:capsa/widgets/capsaapp/generatedvendorbidsdesktopwidget/generated/GeneratedFrame93Widget.dart';


import 'generated/GeneratedFrame84Widget.dart';




/* Instance Vendor Bids / Desktop
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVendorBidsDesktopWidget extends StatelessWidget {
  final BidsModel bidsModel;
  final Widget actionWidget;
  final String title;

  const GeneratedVendorBidsDesktopWidget(this.bidsModel,
      {this.actionWidget, this.title = '', Key key})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
        borderRadius: BorderRadius.circular(25.0),
        elevation: 5,
        child: Container(
          width: 344.0,
          height: Responsive.isMobile(context)
              ? (bidsModel == null ? 240 : 260)
              : 290.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(25.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(25.0),
                  child: Container(
                    color: Color.fromARGB(255, 245, 251, 255),
                  ),
                ),
                Positioned(
                  child: Column(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            SizedBox(
                              width: 288.0,
                              height: 40.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 219.0,
                                      height: 40.0,
                                      child: GeneratedFrame84Widget(bidsModel),
                                    ),
                                    Positioned(
                                      left: 235.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 53.0,
                                      height: 31.0,
                                      child: ClipRRect(
                                        borderRadius: BorderRadius.circular(15.0),
                                        child: Container(
                                          color: Color.fromARGB(255, 242, 153, 74),
                                          child: Center(
                                              child: Text(
                                                (title == '' || title == null)?'''Anchor''':title,
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.171875,
                                                  fontSize: 10.0,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  color: Color.fromARGB(255, 242, 242, 242),

                                                  /* letterSpacing: 0.0, */
                                                ),
                                              )
                                          ),
                                        ),
                                      ),

                                      //GeneratedFrame88Widget(title,bidsModel,),
                                    )
                                  ]),
                            )
                          ],
                        ),
                        GeneratedFrame93Widget(bidsModel),

                        actionWidget == null
                            ? Material(
                          elevation: 5,
                          borderRadius: BorderRadius.circular(25.0),
                          child: Container(
                            width: 306.0,
                            height: 51.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(25.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(25.0),
                                    child: Container(
                                      color: Color.fromARGB(255, 245, 251, 255),
                                      child: Center(
                                        child: RichText(
                                            overflow: TextOverflow.visible,
                                            textAlign: TextAlign.center,
                                            text:   TextSpan(
                                              style: TextStyle(
                                                height: 1.171875,
                                                fontSize: 15.0,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(255, 51, 51, 51),

                                                /* letterSpacing: 0.0, */
                                              ),
                                              children: [
                                                TextSpan(
                                                  text: '''You have ''',
                                                  style: TextStyle(
                                                    height: 1.171875,
                                                    fontSize: 15.0,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w400,

                                                    /* letterSpacing: 0.0, */
                                                  ),
                                                ),
                                                TextSpan(
                                                  text: bidsModel.nofBids + ' Bids ',
                                                  style: TextStyle(
                                                    color: Color.fromARGB(255, 0, 152, 219),

                                                    /* letterSpacing: null, */
                                                  ),
                                                ),
                                                TextSpan(
                                                  text: '''for this invoice''',
                                                  style: TextStyle(
                                                    height: 1.171875,
                                                    fontSize: 15.0,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w400,

                                                    /* letterSpacing: 0.0, */
                                                  ),
                                                )
                                              ],
                                            )),
                                      ),
                                    ),
                                  ),
                                ]),
                          ),
                        )
                            : Container(
                                width: 306.0,
                                height: 80.0,
                                child: actionWidget),
                      ]),
                ),
              ]),
        ));
  }
}
