import 'package:capsa/common/responsive.dart';
import 'package:capsa/vendor-new/model/bids_model.dart';
import 'package:flutter/material.dart';
import 'package:capsa/functions/custom_print.dart';
import 'package:capsa/widgets/capsaapp/generatedvendorbidsdesktopwidget/generated/GeneratedFrame149Widget.dart';
import 'package:capsa/widgets/capsaapp/generatedvendorbidsdesktopwidget/generated/GeneratedFrame93Widget.dart';
import 'package:capsa/widgets/capsaapp/generatedvendorbidsdesktopwidget/generated/GeneratedFrame94Widget.dart';

import 'generated/GeneratedFrame87Widget.dart';
import 'generated/GeneratedFrame89Widget.dart';

/* Instance Vendor Bids / Desktop
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVendorBidsDesktopWidget extends StatelessWidget {
  final BidsModel bidsModel;
  final Widget actionWidget;
  final String title;

  const GeneratedVendorBidsDesktopWidget(this.bidsModel,
      {this.actionWidget, this.title = '', Key key})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
        borderRadius: BorderRadius.circular(25.0),
        elevation: 5,
        child: Container(
          width: 344.0,
          height: Responsive.isMobile(context)
              ? (bidsModel == null ? 240 : 260)
              : 290.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(25.0),
            // boxShadow: [
            //   BoxShadow(
            //     color: Color.fromARGB(25, 0, 0, 0),
            //     offset: Offset(10.0, 10.0),
            //     blurRadius: 10,
            //     spreadRadius: 0.0,
            //   ),
            //   BoxShadow(
            //     color: Color.fromARGB(255, 255, 255, 255),
            //     offset: Offset(-10.0, -10.0),
            //     blurRadius: 0,
            //     spreadRadius: 2.0,
            //   )
            // ],
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(25.0),
                  child: Container(
                    color: Color.fromARGB(255, 245, 251, 255),
                  ),
                ),
                // Positioned.fill(
                //   child: ClipRRect(
                //     borderRadius: BorderRadius.circular(25.0),
                //     child: Image.asset(
                //       "assets/images/6aa12eea9b80620ebca85da47ee3f9835a242774.png",
                //       color: null,
                //       fit: BoxFit.fill,
                //       repeat: ImageRepeat.repeat,
                //       width: 10.0,
                //       height: 10.0,
                //       colorBlendMode: BlendMode.dstATop,
                //     ),
                //   ),
                // ),
                Positioned(
                  child: Column(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            GeneratedFrame89Widget(bidsModel, title: title,),
                            // GeneratedFrame87Widget(),
                            // GeneratedFrame94Widget(bidsModel),
                          ],
                        ),
                        GeneratedFrame93Widget(bidsModel),

                        actionWidget == null
                            ? GeneratedFrame149Widget(bidsModel)
                            : Container(
                                width: 306.0,
                                height: 80.0,
                                child: actionWidget),
                        // else
                        //   Positioned(
                        //       left: Responsive.isMobile(context) ? 18 : 16.0,
                        //       top: Responsive.isMobile(context) ? 170 : 215.0,
                        //       right: null,
                        //       bottom: null,
                        //       width: 306.0,
                        //       height: 80.0,
                        //       child: actionWidget),
                      ]),
                ),
                // Positioned(
                //   top: Responsive.isMobile(context) ? 20 : 24.0,
                //   right: null,
                //   bottom: null,
                //   width: 332.0,
                //   height: 64.0,
                //   child: Row(
                //     mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                //     children: [
                //       GeneratedFrame94Widget(bidsModel),
                //     ],
                //   ),
                // ),
                // Positioned(
                //   left: 16.0,
                //   top: Responsive.isMobile(context) ? 90 : 120.0,
                //   right: null,
                //   bottom: null,
                //   width: 312.0,
                //   height: 63.0,
                //   child: GeneratedFrame93Widget(bidsModel),
                // ),
                // if (actionWidget == null)
                //   Positioned(
                //     top: Responsive.isMobile(context) ? 170 : 215.0,
                //     child: Row(
                //       mainAxisAlignment: MainAxisAlignment.center,
                //       children: [
                //         GeneratedFrame149Widget(bidsModel),
                //         // Positioned(
                //         //   left: Responsive.isMobile(context) ? 18 : 16.0,
                //         //   top: Responsive.isMobile(context) ? 170 : 215.0,
                //         //   right: null,
                //         //   bottom: null,
                //         //   width: 306.0,
                //         //   height: 51.0,
                //         //   child:
                //         // ),
                //       ],
                //     ),
                //   )
                // else
                //   Positioned(
                //       left: Responsive.isMobile(context) ? 18 : 16.0,
                //       top: Responsive.isMobile(context) ? 170 : 215.0,
                //       right: null,
                //       bottom: null,
                //       width: 306.0,
                //       height: 80.0,
                //       child: actionWidget),
              ]),
        ));
  }
}
