import 'package:flutter/material.dart';import 'package:capsa/functions/custom_print.dart';
import 'package:capsa/widgets/capsaapp/generated_mobilemenunavigationsvendorwidget/generated/GeneratedHomeActiveWidget.dart';
import 'package:capsa/widgets/capsaapp/helpers/transform/transform.dart';

/* Instance _Mobile Menu Navigations / Vendor
    Autogenerated by FlutLab FTF Generator
  */
class Generated_MobileMenuNavigationsVendorWidget extends StatelessWidget {
  final List<Map> menuList;

  Generated_MobileMenuNavigationsVendorWidget(this.menuList, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (menuList.length == 0) return Container(height: 0,);

    return Material(
        child: Container(
      width: MediaQuery.of(context).size.width,
      height: 66.0,
      child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: 0,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedHomeActiveWidget(menuList),
                  ))
            ]);
          }),
        )
      ]),
    ));
  }
}
