class BidHistoryModel {
  final String invoiceNumber,
      paymentStatus,
      discount_status,
      discountVal,
      invoiceValue,
      netReturn,
      companyPan,
      investor_pan,
      cust_pan,
      companyName,
      effectiveDueDate,
      transactionsStatus,
      historyStatus,
      email,
      tenure,
      investorName,
      address,
      customerName,
      startDate,
      endDate,
      fileName,
      askRate,
      platFormFee,
      phoneNo,
  currency;
  final DateTime discountedDate;

  BidHistoryModel(
      {this.discountedDate,
      this.invoiceNumber,
      this.email,
      this.phoneNo,
      this.paymentStatus,
      this.discount_status,
      this.discountVal,
      this.invoiceValue,
      this.netReturn,
      this.companyPan,
      this.investor_pan,
      this.cust_pan,
      this.companyName,
      this.effectiveDueDate,
      this.historyStatus,
      this.tenure,
      this.investorName,
      this.customerName,
      this.address,
      this.startDate,
      this.endDate,
      this.fileName,
      this.platFormFee,
      this.askRate: '0',
      this.transactionsStatus,
      this.currency});


  Map<String, dynamic> toLoadPurchaseAggJson() => {
      'cust_pan': cust_pan,
      'customer_name': "",
      'description': "",

      'due_date': effectiveDueDate,
      'eff_due_date': effectiveDueDate,
      'int_rate': askRate,
      'invoice_number': invoiceNumber,
      'invoice_value': invoiceValue,
      'lender_pan': investor_pan,
      'p_type': "0",

      // 'sign_stat': sign_stat,
      // 'start_date': start_date,
      // 'sign_stat': "0",
      // 'digital_name': digital_name,
      // 'digital_name_buyer': digital_name_buyer,
      // 'digital_name_accept_time': digital_name_accept_time,
      // 'digital_name_buyer_accept_time': digital_name_buyer_accept_time,

      'start_date': startDate,
      'ask_amt': "",
  };
}
