/// Flutter icons CurrencyIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CurrencyIcon
///      fonts:
///       - asset: fonts/CurrencyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CurrencyIcon {
  CurrencyIcon._();

  static const _kFontFam = 'CurrencyIcon';
  static const String _kFontPkg = null;

  static const IconData naira = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
