import 'dart:typed_data';

class OpenDealModel {
  final String invoice_value,
      isRevenue,
      start_date,
      due_date,
      eff_due_date,
      minimum_investment,
      invoice_number,
      trans_his,
      description,
      customer_name,
      comp_contract_address,
      child_address,
      discount_percentage,
      discount_status,
      companyName,
      companyPAN,
      companySafePercentage,
      customerCIN,
      industry,
      founded,
      key_person,
      about,
      colour,
      city,
      state,
      website,
      linkedin,
      fb,
      twitter,
      insta,
      customer_pan,
      sel_CIN,
      sel_industry,
      sel_founded,
      sel_key_person,
      sel_about,
      sel_website,
      sel_linkedin,
      sel_fb,
      sel_twitte,
      sel_insta,
      ask_amt,
      ask_rate,
      totalDiscount,
      alcptdy,
  prop_amt,
      isSplit;

  // final Uint8List img;

  OpenDealModel({

    this.invoice_value,
    this.isRevenue,
    this.start_date,
    this.due_date,
    this.eff_due_date,
    this.minimum_investment,
    this.invoice_number,
    this.trans_his,
    this.description,
    this.customer_name,
    this.comp_contract_address,
    this.child_address,
    this.discount_percentage,
    this.discount_status,
    this.companyName,
    this.companyPAN,
    this.companySafePercentage,
    this.customerCIN,
    this.industry,
    this.founded,
    this.key_person,
    this.about,
    this.colour,
    this.city,
    this.state,
    this.website,
    this.linkedin,
    this.fb,
    this.twitter,
    this.insta,
    this.customer_pan,
    this.sel_CIN,
    this.sel_industry,
    this.sel_founded,
    this.sel_key_person,
    this.sel_about,
    this.sel_website,
    this.sel_linkedin,
    this.sel_fb,
    this.sel_twitte,
    this.sel_insta,
    this.ask_amt,
    this.ask_rate,
    this.totalDiscount,
    this.alcptdy,
    this.isSplit = '0',
    this.prop_amt

  });
}
